global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "cats-dogs-api"
    static_configs:
      - targets: ["api:8000"]
    metrics_path: /metrics

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
